### ISSUE TITLE
Theming Issues

### ISSUE THREAD

**Issue by davidsmorais** [davidsmorais/kuro#16]
# Known Theming Issues
This issue aims to centralize all known issues related to the dark/black/sepia theme

- [x] Settings menu color contrast 
- [x] 'My Day' context menu
- [x] 'Add a task' menu buttons while hovered
- [x] Recurrence field sub menus
- [x] `select` and `input` elements theming  
- [x] Adjust tooltips background to theming
- [x] Adjust datepicker theming
- [x] Task deletion confirmation dialogue
- [x] Task 'Add a note' field
